# -*- coding: utf-8 -*-
"""GenAi1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16zwV6vaL2ljY_b-uyKdjgw3xnh5cwH41
"""

!pip install tensorflow-hub tensorflow

import tensorflow_hub as hub
import tensorflow as tf
import numpy as np
import PIL.Image
import matplotlib.pyplot as plt

hub_module = hub.load('https://tfhub.dev/google/magenta/arbitrary-image-stylization-v1-256/2')

from google.colab import drive
drive.mount('/content/drive')

def load_img(path_to_img):
  max_dim = 512
  img = tf.io.read_file(path_to_img)
  img = tf.image.decode_image(img, channels=3)
  img = tf.image.convert_image_dtype(img, tf.float32)

  shape = tf.cast(tf.shape(img)[:-1], tf.float32)
  long_dim = max(shape)
  scale = max_dim / long_dim

  new_shape = tf.cast(shape * scale, tf.int32)

  img = tf.image.resize(img, new_shape)
  img = img[tf.newaxis, :]
  return img
content_image_path = '/content/drive/MyDrive/portrait.jpg'
content_image = load_img(content_image_path)
style_image_path = '/content/drive/MyDrive/styleimage.jpg'
style_image = load_img(style_image_path)

stylized_image = hub_module(tf.constant(content_image), tf.constant(style_image))[0]

plt.imshow(np.squeeze(stylized_image))
plt.show()